spring:
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

  cloud:
    gateway:
      routes:
        - id: post_route
          uri: ${TARGET_URI:https://jsonplaceholder.typicode.com}
          predicates:
            - Path=/posts/**
          filters:
            - JwtAuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: ${RATE_LIMIT_REPLENISH:2}
                redis-rate-limiter.burstCapacity: ${RATE_LIMIT_BURST:5}
                key-resolver: "#{@ipKeyResolver}"